version: '3.9'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: forum_container
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - docker.env
  #   networks:
  #     - postgres_network
  #     - elastic_network

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres_network

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    container_name: es01_container
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - elastic_network

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    container_name: es02_container
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - elastic_network

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    container_name: es03_container
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - elastic_network

volumes:
  pgdata:
  pgadmin_data:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  postgres_network:
    driver: bridge
  elastic_network:
    driver: bridge
